import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ListGuest from "./components/navigation/lists";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AnTCV",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./favicon.png" sizes="any" type="image/png" />
      </head>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}